### ISSUE TITLE
Error running marko-language-server command on Windows

### ISSUE THREAD

**Issue by russell-knight** [marko-js/language-server#301]
### Details
Receiving the below error when running the marko-language-server command

### Your Environment

- Windows 11
- Node.js v20.10.0

### Stack Trace

```
C:\src\landing-pages [main ≡]> marko-language-server
C:\Users\<User>\AppData\Roaming\npm\node_modules\@marko\language-server\node_modules\vscode-languageserver\lib\node\main.js:192
        throw new Error('Connection input stream is not set. ' + commandLineMessage);
        ^

Error: Connection input stream is not set. Use arguments of createConnection or set command line parameters: '--node-ipc', '--stdio' or '--socket={number}'
    at _createConnection (C:\Users\<User>\AppData\Roaming\npm\node_modules\@marko\language-server\node_modules\vscode-languageserver\lib\node\main.js:192:15)
    at createConnection (C:\Users\<User>\AppData\Roaming\npm\node_modules\@marko\language-server\node_modules\vscode-languageserver\lib\node\main.js:137:12)
    at Object.<anonymous> (C:\Users\<User>\AppData\Roaming\npm\node_modules\@marko\language-server\dist\index.js:3715:52)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\<User>\AppData\Roaming\npm\node_modules\@marko\language-server\bin.js:2:1)

Node.js v20.10.0
```
</details>

**Comment by DylanPiercey** [comment]
This particular error means that no arguments were passed to the language-server cli (either `'--node-ipc', '--stdio' or '--socket={number}'`) which one you'd used would depend on the lsp client in whatever host your running.
